// Omnea API Contract derived from Postman Collections

export interface APIEndpoint {
  id: string;
  name: string;
  method: "GET" | "POST" | "PATCH" | "PUT" | "DELETE" | "CSV";
  path: string;
  description: string;
  collection: string;
  auth: string;
  pathParams: { key: string; description: string }[];
  bodyParams?: { key: string; type: string; description: string; required?: boolean }[];
  testScript?: string;
}

export const omneaEndpoints: APIEndpoint[] = [
    // Internal Contacts
    // Custom Data (global endpoints)
    {
      id: "get-custom-data-record-by-id",
      name: "Get custom data record by ID",
      method: "GET",
      path: "{{baseUrl}}/v1/custom-data/{{customDataSlug}}/records/{{customDataRecordId}}",
      description: "Retrieve a single custom data record by ID.",
      collection: "Custom Data",
      auth: "Bearer {{accessToken}}",
      pathParams: [
        { key: "customDataSlug", description: "Slug identifier for the custom data" },
        { key: "customDataRecordId", description: "Custom data record UUID" }
      ],
    },
    {
      id: "get-custom-data-record-by-remote-id",
      name: "Get custom data record by remote ID",
      method: "GET",
      path: "{{baseUrl}}/v1/by-remote-id/custom-data/{{customDataSlug}}/records/{{remoteId}}",
      description: "Retrieve a single custom data record by remote ID.",
      collection: "Custom Data",
      auth: "Bearer {{accessToken}}",
      pathParams: [
        { key: "customDataSlug", description: "Slug identifier for the custom data" },
        { key: "remoteId", description: "Remote identifier for the custom data record" }
      ],
    },
    {
      id: "update-custom-data-record-by-id",
      name: "Update custom data record by ID",
      method: "PATCH",
      path: "{{baseUrl}}/v1/custom-data/{{customDataSlug}}/records/{{customDataRecordId}}",
      description: "Update a custom data record by ID.",
      collection: "Custom Data",
      auth: "Bearer {{accessToken}}",
      pathParams: [
        { key: "customDataSlug", description: "Slug identifier for the custom data" },
        { key: "customDataRecordId", description: "Custom data record UUID" }
      ],
      bodyParams: [
        { key: "value", type: "string", description: "Value of the custom data record" },
        { key: "remoteId", type: "string", description: "Remote identifier for the custom data record" },
        { key: "isArchived", type: "boolean", description: "Whether the record is archived" },
        { key: "dependsOn", type: "object", description: "Optional dependsOn object" },
      ],
    },
          {
            id: "update-custom-data-record-by-remote-id",
            name: "Update custom data record by remote ID",
            method: "PATCH",
            path: "{{baseUrl}}/v1/by-remote-id/custom-data/{{customDataSlug}}/records/{{remoteId}}",
            description: "Update a custom data record by remote ID.",
            collection: "Custom Data",
            auth: "Bearer {{accessToken}}",
            pathParams: [
              { key: "customDataSlug", description: "Slug identifier for the custom data" },
              { key: "remoteId", description: "Remote identifier for the custom data record" }
            ],
            bodyParams: [
              { key: "value", type: "string", description: "Value of the custom data record" },
              { key: "remoteId", type: "string", description: "Remote identifier for the custom data record" },
              { key: "isArchived", type: "boolean", description: "Whether the record is archived" },
              { key: "dependsOn", type: "object", description: "Optional dependsOn object" },
            ],
          },
        // Subsidiaries (global endpoints)
        {
          id: "list-all-subsidiaries",
          name: "List subsidiaries",
          method: "GET",
          path: "{{baseUrl}}/v1/subsidiaries",
          description: "Get a paginated list of subsidiaries.",
          collection: "Subsidiaries",
          auth: "Bearer {{accessToken}}",
          pathParams: [
            { key: "limit", description: "Query param: 1-100 (default: 100)" },
            { key: "cursor", description: "Query param: pagination cursor" },
            { key: "sort", description: "Query param: name|-name|createdAt|-createdAt|updatedAt|-updatedAt" },
            { key: "filter", description: "Query param: OData filter (URL encoded)" },
          ],
        },
        {
          id: "get-subsidiary-by-id",
          name: "Get a subsidiary by ID",
          method: "GET",
          path: "{{baseUrl}}/v1/subsidiaries/{{subsidiaryId}}",
          description: "Get a subsidiary by ID.",
          collection: "Subsidiaries",
          auth: "Bearer {{accessToken}}",
          pathParams: [ { key: "subsidiaryId", description: "The unique identifier of the subsidiary (UUID)" } ],
        },
        {
          id: "get-subsidiary-by-remote-id",
          name: "Get a subsidiary by remote ID",
          method: "GET",
          path: "{{baseUrl}}/v1/by-remote-id/subsidiaries/{{remoteId}}",
          description: "Get a subsidiary by remote ID.",
          collection: "Subsidiaries",
          auth: "Bearer {{accessToken}}",
          pathParams: [ { key: "remoteId", description: "The remote ID of the subsidiary, must be URL encoded" } ],
        },
        {
          id: "create-subsidiaries-batch",
          name: "Create subsidiaries",
          method: "POST",
          path: "{{baseUrl}}/v1/subsidiaries/batch",
          description: "Create new subsidiaries.",
          collection: "Subsidiaries",
          auth: "Bearer {{accessToken}}",
          pathParams: [],
          bodyParams: [
            { key: "subsidiaries", type: "array", description: "Array of subsidiaries to create (1–100 items)", required: true },
            { key: "subsidiaries[].name", type: "string", description: "Name of the subsidiary (1–255 chars)", required: true },
            { key: "subsidiaries[].remoteId", type: "string", description: "External system identifier, must be unique (1–255 chars)", required: true },
            { key: "subsidiaries[].dependsOn", type: "object", description: "Optional dependsOn object" },
          ],
        },
        {
          id: "update-subsidiary-by-id",
          name: "Update a subsidiary",
          method: "PATCH",
          path: "{{baseUrl}}/v1/subsidiaries/{{subsidiaryId}}",
          description: "Update an existing subsidiary.",
          collection: "Subsidiaries",
          auth: "Bearer {{accessToken}}",
          pathParams: [ { key: "subsidiaryId", description: "The unique identifier of the subsidiary (UUID)" } ],
          bodyParams: [
            { key: "name", type: "string", description: "Name of the subsidiary" },
            { key: "remoteId", type: "string", description: "External system identifier" },
            { key: "isArchived", type: "boolean", description: "Whether the subsidiary is archived" },
            { key: "dependsOn", type: "object", description: "Optional dependsOn object" },
          ],
        },
        {
          id: "update-subsidiary-by-remote-id",
          name: "Update a subsidiary by remote ID",
          method: "PATCH",
          path: "{{baseUrl}}/v1/by-remote-id/subsidiaries/{{remoteId}}",
          description: "Update an existing subsidiary by external system identifier.",
          collection: "Subsidiaries",
          auth: "Bearer {{accessToken}}",
          pathParams: [ { key: "remoteId", description: "The remote ID of the subsidiary, must be URL encoded" } ],
          bodyParams: [
            { key: "name", type: "string", description: "Name of the subsidiary" },
            { key: "remoteId", type: "string", description: "New external system identifier" },
            { key: "isArchived", type: "boolean", description: "Whether the subsidiary is archived" },
            { key: "dependsOn", type: "object", description: "Optional dependsOn object" },
          ],
        },
      {
      id: "list-internal-contacts",
      name: "List internal contacts",
      method: "GET",
      path: "{{baseUrl}}/v1/suppliers/{{supplierId}}/internal-contacts",
      description: "Get a paginated list of internal contacts for a supplier.",
      collection: "Internal Contacts",
      auth: "Bearer {{accessToken}}",
      pathParams: [
        { key: "supplierId", description: "Omnea supplier UUID" },
        { key: "limit", description: "Query param: 1-100 (default: 100)" },
        { key: "cursor", description: "Query param: pagination cursor" },
        { key: "sort", description: "Query param: createdAt|-createdAt (default: -createdAt)" },
        { key: "filter", description: "Query param: OData filter (URL encoded)" },
      ],
      testScript: `Logs: id, role, title, user (id, email, firstName, lastName), createdAt, updatedAt. Supports pagination.`,
    },
    {
      id: "create-internal-contacts-batch",
      name: "Create internal contacts (batch)",
      method: "POST",
      path: "{{baseUrl}}/v1/suppliers/{{supplierId}}/internal-contacts/batch",
      description: "Create new internal contacts for a supplier in a single batch request (1-100 items).",
      collection: "Internal Contacts",
      auth: "Bearer {{accessToken}}",
      pathParams: [
        { key: "supplierId", description: "Omnea supplier UUID" },
      ],
      bodyParams: [
        { key: "internalContacts", type: "array<object>", description: "Array of internal contacts to create (required, length 1-100)", required: true },
        { key: "internalContacts[].role", type: "string", description: "Contact role (required)", required: true },
        { key: "internalContacts[].title", type: "string|null", description: "Contact title (required)", required: true },
        { key: "internalContacts[].user", type: "object", description: "User object (required)", required: true },
      ],
      testScript: `Expects 200 with data[] of created contacts (id, role, title, user, createdAt, updatedAt).`,
    },
  // Authentication
  {
    id: "auth-token",
    name: "Request an access token",
    method: "POST",
    path: "https://auth.omnea.co/oauth2/token",
    description: "OAuth 2.0 Client Credentials flow. Returns access_token for subsequent API calls.",
    collection: "Authentication",
    auth: "none",
    pathParams: [],
    bodyParams: [
      { key: "grant_type", type: "string", description: "Required constant: client_credentials", required: true },
      { key: "client_id", type: "string", description: "Omnea-provided ID", required: true },
      { key: "client_secret", type: "string", description: "Omnea-provided secret", required: true },
      { key: "scope", type: "string", description: "public-api/read (recommended for full object retrieval)" },
    ],
    testScript: `pm.test("Status code is 200"); → pm.environment.set("accessToken", jsonData.access_token);`,
  },
  // Suppliers
  {
    id: "get-suppliers",
    name: "Get suppliers",
    method: "GET",
    path: "{{baseUrl}}/v1/suppliers",
    description: "List all suppliers. Logs a clean schema of the first supplier's fields including standard, address, and custom fields.",
    collection: "Suppliers",
    auth: "Bearer {{accessToken}}",
    pathParams: [],
    testScript: `Logs: Id, Name, State, RemoteId, TaxNumber, Address.*, CustomFields.* → Sets active_supplier_id`,
  },
  {
    id: "get-supplier-by-id",
    name: "Get Supplier by ID",
    method: "GET",
    path: "{{baseUrl}}/v1/suppliers/{{supplier_id}}",
    description: "Get full supplier details by Omnea ID. Maps Overview, Financial, Custom, and Sync Status sections.",
    collection: "Suppliers",
    auth: "Bearer {{accessToken}}",
    pathParams: [{ key: "supplier_id", description: "Omnea supplier UUID" }],
    testScript: `Logs: Overview (name, website, taxNumber, address), Financial (isPreferred, paymentMethod), Custom (entity-type, materiality-level, infosec tiers, corporate-registration-number, CS/KYC/SCA status), Sync (remoteId, remoteLink, state)`,
  },
  {
    id: "get-supplier-by-remote-id",
    name: "Get Supplier by remote ID",
    method: "GET",
    path: "{{baseUrl}}/v1/by-remote-id/suppliers/{{supplierRemoteId}}",
    description: "Look up supplier using BC Vendor No (remoteId). Critical for BC→Omnea identity resolution.",
    collection: "Suppliers",
    auth: "Bearer {{accessToken}}",
    pathParams: [{ key: "supplierRemoteId", description: "BC Vendor ID (e.g., V03624)" }],
  },
  {
    id: "get-suppliers-by-csv",
    name: "Find suppliers by CSV",
    method: "CSV",
    path: "{{baseUrl}}/v1/suppliers",
    description: "Upload a single-column CSV of supplier names and fuzzy-match them against all suppliers in Omnea. Shows matched and unmatched results.",
    collection: "Suppliers",
    auth: "Bearer {{accessToken}}",
    pathParams: [],
  },
  {
    id: "create-suppliers-batch",
    name: "Create Suppliers (Batch)",
    method: "POST",
    path: "{{baseUrl}}/v1/suppliers/batch",
    description: "Create multiple suppliers in a single request. Supports name, legal name, entity type, tax number, remote ID, address, and custom fields per supplier.",
    collection: "Suppliers",
    auth: "Bearer {{accessToken}}",
    pathParams: [],
    bodyParams: [
      { key: "suppliers", type: "array", description: "Array of supplier objects to create", required: true },
      { key: "suppliers[].name", type: "string", description: "Supplier name (required)", required: true },
      { key: "suppliers[].legalName", type: "string", description: "Legal entity name" },
      { key: "suppliers[].entityType", type: "string", description: "company, individual, etc." },
      { key: "suppliers[].state", type: "string", description: "active, inactive" },
      { key: "suppliers[].taxNumber", type: "string", description: "Tax/VAT ID" },
      { key: "suppliers[].remoteId", type: "string", description: "BC Vendor No or external reference" },
      { key: "suppliers[].address", type: "object", description: "Address with street1, street2, city, state, country, zipCode" },
      { key: "suppliers[].customFields", type: "object", description: "Custom field objects with value property" },
    ],
  },
  {
    id: "update-supplier",
    name: "Update Supplier by ID",
    method: "PATCH",
    path: "{{baseUrl}}/v1/suppliers/{{supplier_id}}",
    description: "Update supplier fields (name, legalName, state, address, customFields).",
    collection: "Supplier Maintenance",
    auth: "Bearer {{accessToken}}",
    pathParams: [{ key: "supplier_id", description: "Omnea supplier UUID" }],
    bodyParams: [
      { key: "name", type: "string", description: "Supplier name" },
      { key: "legalName", type: "string", description: "Legal name" },
      { key: "state", type: "string", description: "active or inactive" },
      { key: "address", type: "object", description: "Address object" },
      { key: "customFields", type: "object", description: "Custom fields map" },
    ],
  },
  {
    id: "create-supplier-external-contacts-batch",
    name: "Create external contacts",
    method: "POST",
    path: "{{baseUrl}}/v1/suppliers/{{supplierId}}/external-contacts/batch",
    description: "Create new external contacts for a supplier in a single batch request (1-100 items).",
    collection: "Suppliers",
    auth: "Bearer {{accessToken}}",
    pathParams: [{ key: "supplierId", description: "The unique identifier (UUID) of the supplier" }],
    bodyParams: [
      {
        key: "externalContacts",
        type: "array<object>",
        description: "Array of external contacts to create (required, length 1-100)",
        required: true,
      },
      { key: "externalContacts[].email", type: "string", description: "Contact email", required: true },
      { key: "externalContacts[].firstName", type: "string | null", description: "First name", required: true },
      { key: "externalContacts[].lastName", type: "string | null", description: "Last name", required: true },
      { key: "externalContacts[].userId", type: "string | null", description: "Linked user ID" },
      { key: "externalContacts[].title", type: "string | null", description: "Job title", required: true },
      { key: "externalContacts[].isPrimary", type: "boolean", description: "Whether this is the primary contact" },
      { key: "externalContacts[].phoneNumber", type: "string | null", description: "Phone number" },
      { key: "externalContacts[].createdAt", type: "date-time", description: "Created timestamp" },
      { key: "externalContacts[].updatedAt", type: "date-time", description: "Updated timestamp" },
    ],
    testScript: `Expects 200 with data[] of created contacts (id, email, firstName, lastName, userId, title, isPrimary, phoneNumber, createdAt, updatedAt).`,
  },
  // Supplier Profiles
  {
    id: "get-profiles-by-supplier",
    name: "Get Supplier Profiles by Supplier ID",
    method: "GET",
    path: "{{baseUrl}}/v1/suppliers/{{active_supplier_id}}/profiles",
    description: "List all subsidiary profiles for a supplier. Maps profile state, subsidiary, payment method/terms, and custom fields.",
    collection: "Supplier Profile",
    auth: "Bearer {{accessToken}}",
    pathParams: [{ key: "active_supplier_id", description: "Omnea supplier UUID" }],
    testScript: `For each profile: id, state, subsidiary (id, name, remoteId), paymentMethod, paymentTerms, customFields (supplierProfileRelationshipOwner with email)`,
  },
  {
    id: "get-profiles-by-remote-id",
    name: "Get Supplier Profiles by remote ID",
    method: "GET",
    path: "{{baseUrl}}/v1/by-remote-id/suppliers/{{supplierRemoteId}}/profiles",
    description: "Look up profiles by BC Vendor No. Returns all subsidiary relationships for the BC vendor.",
    collection: "Supplier Profile",
    auth: "Bearer {{accessToken}}",
    pathParams: [{ key: "supplierRemoteId", description: "BC Vendor ID" }],
    testScript: `Logs: Profile ID, Wise Subsidiary name, Status, Payment Method/Terms, Relationship Owner Email`,
  },
  {
    id: "get-profile-by-subsidiary",
    name: "Get Supplier Profile by subsidiary ID",
    method: "GET",
    path: "{{baseUrl}}/v1/suppliers/{{supplier_id}}/profiles/{{subsidiary_id}}",
    description: "Get specific profile for a supplier-subsidiary combination. Shows attached UI fields and system metadata.",
    collection: "Supplier Profile",
    auth: "Bearer {{accessToken}}",
    pathParams: [
      { key: "supplier_id", description: "Omnea supplier UUID" },
      { key: "subsidiary_id", description: "Omnea subsidiary UUID" },
    ],
    testScript: `Attached: subsidiary.name, state, remoteId, remoteLink, paymentMethod.name, paymentTerms.name, Relationship Owner. System: id, subsidiary.id, createdAt, updatedAt`,
  },
  {
    id: "get-profile-by-subsidiary-remote",
    name: "Get profile by subsidiary remote ID",
    method: "GET",
    path: "{{baseUrl}}/v1/by-remote-id/suppliers/{{supplierRemoteId}}/profiles/{{subsidiaryRemoteId}}",
    description: "Look up specific subsidiary profile using both BC Vendor No and BC Subsidiary Remote ID.",
    collection: "Supplier Profile",
    auth: "Bearer {{accessToken}}",
    pathParams: [
      { key: "supplierRemoteId", description: "BC Vendor ID" },
      { key: "subsidiaryRemoteId", description: "BC Subsidiary Remote ID" },
    ],
  },
  {
    id: "update-profile",
    name: "Update supplier profile by subsidiary ID",
    method: "PATCH",
    path: "{{baseUrl}}/v1/suppliers/{{supplier_id}}/profiles/{{subsidiary_id}}",
    description: "PATCH to write remoteId (BC Vendor No) and remoteLink back to Omnea. This is the 'handshake' that closes the loop.",
    collection: "Supplier Profile",
    auth: "Bearer {{accessToken}}",
    pathParams: [
      { key: "supplier_id", description: "Omnea supplier UUID" },
      { key: "subsidiary_id", description: "Omnea subsidiary UUID" },
    ],
    bodyParams: [
      { key: "remoteId", type: "string", description: "BC Vendor No (e.g., V03624)", required: true },
      { key: "remoteLink", type: "string", description: "BC vendor card URL" },
      { key: "state", type: "string", description: "Profile state (e.g., active)" },
    ],
    testScript: `Verifies: remoteId sent === remoteId returned. Logs SYNC UPDATE confirmation.`,
  },
  // Bank Accounts
  {
    id: "list-bank-accounts",
    name: "List bank accounts for supplier profile",
    method: "GET",
    path: "{{baseUrl}}/v1/suppliers/{{supplier_id}}/profiles/{{subsidiary_id}}/bank-accounts",
    description: "List all bank accounts attached to a supplier profile. Maps UI fields and system metadata.",
    collection: "Bank Account",
    auth: "Bearer {{accessToken}}",
    pathParams: [
      { key: "supplier_id", description: "Omnea supplier UUID" },
      { key: "subsidiary_id", description: "Omnea subsidiary/profile UUID" },
    ],
    testScript: `Attached: accountName, bankName, accountNumber, sortCode, iban, swiftCode, currency.code, isActive, address.*. System: id, remoteId, currency.id, createdAt, updatedAt`,
  },
  {
    id: "update-bank-account",
    name: "Update bank account with BC ID",
    method: "PATCH",
    path: "{{baseUrl}}/v1/suppliers/{{supplier_id}}/profiles/{{profile_id}}/bank-accounts/{{bank_account_id}}",
    description: "PATCH to write BC Bank Code (remoteId) to the bank account. Closes the BC sync loop for banking.",
    collection: "Bank Account",
    auth: "Bearer {{accessToken}}",
    pathParams: [
      { key: "supplier_id", description: "Omnea supplier UUID" },
      { key: "profile_id", description: "Omnea profile UUID" },
      { key: "bank_account_id", description: "Omnea bank account UUID" },
    ],
    bodyParams: [
      { key: "remoteId", type: "string", description: "BC Bank Code (e.g., BC-BANK-001)", required: true },
    ],
    testScript: `Verifies: remoteId sent === remoteId returned. Logs LOOP CLOSED: BC SYNC CONFIRMED.`,
  },
  // Departments
  {
    id: "list-departments",
    name: "List departments",
    method: "GET",
    path: "{{baseUrl}}/v1/departments",
    description: "Get a paginated list of departments. Supports limit, cursor, sort, and OData filter.",
    collection: "Departments",
    auth: "Bearer {{accessToken}}",
    pathParams: [
      { key: "limit", description: "Query param: 1-100 (default: 100)" },
      { key: "cursor", description: "Query param: pagination cursor" },
      { key: "sort", description: "Query param: name|-name|createdAt|-createdAt|updatedAt|-updatedAt" },
      { key: "filter", description: "Query param: OData filter (URL encoded)" },
    ],
    testScript: `Logs: id, name, remoteId, isArchived, createdAt, updatedAt. Supports automatic pagination in tester.`,
  },
  {
    id: "get-department-by-id",
    name: "Get department by ID",
    method: "GET",
    path: "{{baseUrl}}/v1/departments/{{departmentId}}",
    description: "Get a single department by UUID.",
    collection: "Departments",
    auth: "Bearer {{accessToken}}",
    pathParams: [{ key: "departmentId", description: "Department UUID" }],
  },
  {
    id: "update-department",
    name: "Update department",
    method: "PATCH",
    path: "{{baseUrl}}/v1/departments/{{departmentId}}",
    description: "Update an existing department by UUID.",
    collection: "Departments",
    auth: "Bearer {{accessToken}}",
    pathParams: [{ key: "departmentId", description: "Department UUID" }],
    bodyParams: [
      { key: "name", type: "string", description: "Department name (1-255)" },
      { key: "remoteId", type: "string", description: "External identifier (1-255)" },
      { key: "isArchived", type: "boolean", description: "Archive status" },
      { key: "dependsOn", type: "object", description: "Dependency object" },
    ],
  },
  // Custom Data
  {
    id: "list-custom-data",
    name: "List custom data",
    method: "GET",
    path: "{{baseUrl}}/v1/custom-data",
    description: "Get a paginated list of custom data. Supports limit, cursor, sort, and OData filter.",
    collection: "Custom Data",
    auth: "Bearer {{accessToken}}",
    pathParams: [
      { key: "limit", description: "Query param: 1-100 (default: 100)" },
      { key: "cursor", description: "Query param: pagination cursor" },
      { key: "sort", description: "Query param: name|-name|createdAt|-createdAt|updatedAt|-updatedAt" },
      { key: "filter", description: "Query param: OData filter (URL encoded)" },
    ],
  },
  {
    id: "get-custom-data-by-slug",
    name: "Get custom data by slug",
    method: "GET",
    path: "{{baseUrl}}/v1/custom-data/{{customDataSlug}}",
    description: "Retrieve a single custom data by slug.",
    collection: "Custom Data",
    auth: "Bearer {{accessToken}}",
    pathParams: [{ key: "customDataSlug", description: "Slug identifier" }],
  },
  {
    id: "list-custom-data-records",
    name: "List custom data records",
    method: "GET",
    path: "{{baseUrl}}/v1/custom-data/{{customDataSlug}}/records",
    description: "Get a paginated list of records for a custom data slug.",
    collection: "Custom Data",
    auth: "Bearer {{accessToken}}",
    pathParams: [
      { key: "customDataSlug", description: "Slug identifier" },
      { key: "limit", description: "Query param: 1-100 (default: 100)" },
      { key: "cursor", description: "Query param: pagination cursor" },
      { key: "sort", description: "Query param: value|-value|createdAt|-createdAt|updatedAt|-updatedAt" },
    ],
  },
  {
    id: "create-custom-data-records-batch",
    name: "Create custom data records (batch)",
    method: "POST",
    path: "{{baseUrl}}/v1/custom-data/{{customDataSlug}}/records/batch",
    description: "Create custom data records for a specific custom data slug (max 100).",
    collection: "Custom Data",
    auth: "Bearer {{accessToken}}",
    pathParams: [{ key: "customDataSlug", description: "Slug identifier" }],
    bodyParams: [
      { key: "records", type: "array", description: "Array of records", required: true },
      { key: "records[].remoteId", type: "string", description: "External identifier", required: true },
      { key: "records[].value", type: "string", description: "Record value", required: true },
      { key: "records[].dependsOn", type: "object", description: "Optional dependency object" },
    ],
  },
  // Supplier Maintenance
  {
    id: "update-supplier-by-remote-id",
    name: "Update supplier by remote ID",
    method: "PATCH",
    path: "{{baseUrl}}/v1/by-remote-id/suppliers/{{remoteId}}",
    description: "Update supplier by BC Vendor No (remoteId)",
    collection: "Supplier Maintenance",
    auth: "Bearer {{accessToken}}",
    pathParams: [ { key: "remoteId", description: "BC Vendor No (remoteId)" } ],
    bodyParams: [ { key: "name", type: "string", description: "Supplier name" }, { key: "legalName", type: "string", description: "Legal name" }, { key: "state", type: "string", description: "active or inactive" }, { key: "address", type: "object", description: "Address object" }, { key: "customFields", type: "object", description: "Custom fields map" } ],
  },
  {
    id: "batch-update-suppliers",
    name: "Batch update suppliers",
    method: "PATCH",
    path: "{{baseUrl}}/v1/suppliers/batch",
    description: "Batch update multiple suppliers.",
    collection: "Supplier Maintenance",
    auth: "Bearer {{accessToken}}",
    pathParams: [],
    bodyParams: [ { key: "suppliers", type: "array", description: "Array of supplier objects to update", required: true } ],
  },

  // Supplier Profile (add missing endpoints)
  {
    id: "create-profile",
    name: "Create supplier profile",
    method: "POST",
    path: "{{baseUrl}}/v1/suppliers/{{supplier_id}}/profiles",
    description: "Create a new subsidiary profile.",
    collection: "Supplier Profile",
    auth: "Bearer {{accessToken}}",
    pathParams: [ { key: "supplier_id", description: "Omnea supplier UUID" } ],
    bodyParams: [ { key: "subsidiaryName", type: "string", description: "Subsidiary name", required: true }, { key: "paymentTerms", type: "string", description: "Payment terms" }, { key: "paymentMethod", type: "string", description: "Payment method" }, { key: "state", type: "string", description: "Profile state" }, { key: "customFields", type: "object", description: "Custom fields map" } ],
  },
  {
    id: "patch-profile-by-remote-id",
    name: "Update profile by subsidiary remote ID",
    method: "PATCH",
    path: "{{baseUrl}}/v1/by-remote-id/suppliers/{{remoteId}}/profiles/{{subRemoteId}}",
    description: "Update profile by BC remote IDs.",
    collection: "Supplier Profile",
    auth: "Bearer {{accessToken}}",
    pathParams: [ { key: "remoteId", description: "BC Vendor No (remoteId)" }, { key: "subRemoteId", description: "BC Subsidiary Remote ID" } ],
    bodyParams: [ { key: "remoteId", type: "string", description: "BC Vendor No" }, { key: "remoteLink", type: "string", description: "BC vendor card URL" }, { key: "state", type: "string", description: "Profile state" } ],
  },
  {
    id: "batch-create-profiles-by-remote-id",
    name: "Batch create profiles by supplier remote ID",
    method: "POST",
    path: "{{baseUrl}}/v1/by-remote-id/suppliers/{{remoteId}}/profiles/batch",
    description: "Batch create profiles by supplier remote ID.",
    collection: "Supplier Profile",
    auth: "Bearer {{accessToken}}",
    pathParams: [ { key: "remoteId", description: "BC Vendor No (remoteId)" } ],
    bodyParams: [ { key: "profiles", type: "array", description: "Array of profiles to create", required: true } ],
  },

  // Internal Contacts (add missing endpoints)
  {
    id: "get-internal-contact-by-id",
    name: "Get internal contact by ID",
    method: "GET",
    path: "{{baseUrl}}/v1/suppliers/{{supplierId}}/internal-contacts/{{contactId}}",
    description: "Get internal contact by UUID.",
    collection: "Internal Contacts",
    auth: "Bearer {{accessToken}}",
    pathParams: [ { key: "supplierId", description: "Omnea supplier UUID" }, { key: "contactId", description: "Contact UUID" } ],
  },
  {
    id: "patch-internal-contact",
    name: "Update internal contact",
    method: "PATCH",
    path: "{{baseUrl}}/v1/suppliers/{{supplierId}}/internal-contacts/{{contactId}}",
    description: "Update internal contact role/title.",
    collection: "Internal Contacts",
    auth: "Bearer {{accessToken}}",
    pathParams: [ { key: "supplierId", description: "Omnea supplier UUID" }, { key: "contactId", description: "Contact UUID" } ],
    bodyParams: [ { key: "role", type: "string", description: "Contact role" }, { key: "title", type: "string", description: "Contact title" } ],
  },
  {
    id: "delete-internal-contact",
    name: "Delete internal contact",
    method: "DELETE",
    path: "{{baseUrl}}/v1/suppliers/{{supplierId}}/internal-contacts/{{contactId}}",
    description: "Delete (remove) internal contact.",
    collection: "Internal Contacts",
    auth: "Bearer {{accessToken}}",
    pathParams: [ { key: "supplierId", description: "Omnea supplier UUID" }, { key: "contactId", description: "Contact UUID" } ],
  },
  {
    id: "list-internal-contacts-by-remote-id",
    name: "List internal contacts by supplier remote ID",
    method: "GET",
    path: "{{baseUrl}}/v1/by-remote-id/suppliers/{{remoteId}}/internal-contacts",
    description: "List internal contacts by supplier remote ID.",
    collection: "Internal Contacts",
    auth: "Bearer {{accessToken}}",
    pathParams: [ { key: "remoteId", description: "BC Vendor No (remoteId)" } ],
  },
  {
    id: "batch-create-internal-contacts-by-remote-id",
    name: "Create contacts by supplier remote ID",
    method: "POST",
    path: "{{baseUrl}}/v1/by-remote-id/suppliers/{{remoteId}}/internal-contacts/batch",
    description: "Create contacts by supplier remote ID.",
    collection: "Internal Contacts",
    auth: "Bearer {{accessToken}}",
    pathParams: [ { key: "remoteId", description: "BC Vendor No (remoteId)" } ],
    bodyParams: [ { key: "internalContacts", type: "array", description: "Array of internal contacts to create", required: true } ],
  },
  {
    id: "get-internal-contact-by-remote-id",
    name: "Get internal contact by supplier remote ID",
    method: "GET",
    path: "{{baseUrl}}/v1/by-remote-id/suppliers/{{remoteId}}/internal-contacts/{{contactId}}",
    description: "Get internal contact by supplier remote ID + contact UUID.",
    collection: "Internal Contacts",
    auth: "Bearer {{accessToken}}",
    pathParams: [ { key: "remoteId", description: "BC Vendor No (remoteId)" }, { key: "contactId", description: "Contact UUID" } ],
  },
  {
    id: "patch-internal-contact-by-remote-id",
    name: "Update contact by supplier remote ID",
    method: "PATCH",
    path: "{{baseUrl}}/v1/by-remote-id/suppliers/{{remoteId}}/internal-contacts/{{contactId}}",
    description: "Update contact by supplier remote ID.",
    collection: "Internal Contacts",
    auth: "Bearer {{accessToken}}",
    pathParams: [ { key: "remoteId", description: "BC Vendor No (remoteId)" }, { key: "contactId", description: "Contact UUID" } ],
    bodyParams: [ { key: "role", type: "string", description: "Contact role" }, { key: "title", type: "string", description: "Contact title" } ],
  },
  {
    id: "delete-internal-contact-by-remote-id",
    name: "Delete contact by supplier remote ID",
    method: "DELETE",
    path: "{{baseUrl}}/v1/by-remote-id/suppliers/{{remoteId}}/internal-contacts/{{contactId}}",
    description: "Delete contact by supplier remote ID.",
    collection: "Internal Contacts",
    auth: "Bearer {{accessToken}}",
    pathParams: [ { key: "remoteId", description: "BC Vendor No (remoteId)" }, { key: "contactId", description: "Contact UUID" } ],
  },

  // External Contacts
  {
    id: "create-external-contacts-batch",
    name: "Create external contacts (batch)",
    method: "POST",
    path: "{{baseUrl}}/v1/suppliers/{{supplierId}}/external-contacts/batch",
    description: "Create external contacts for a supplier.",
    collection: "External Contacts",
    auth: "Bearer {{accessToken}}",
    pathParams: [ { key: "supplierId", description: "Omnea supplier UUID" } ],
    bodyParams: [ { key: "externalContacts", type: "array", description: "Array of external contacts to create", required: true } ],
  },

  // Bank Account (add missing endpoints)
  {
    id: "create-bank-account",
    name: "Create bank account",
    method: "POST",
    path: "{{baseUrl}}/v1/suppliers/{{supplier_id}}/profiles/{{profile_id}}/bank-accounts",
    description: "Create a bank account on a profile.",
    collection: "Bank Account",
    auth: "Bearer {{accessToken}}",
    pathParams: [ { key: "supplier_id", description: "Omnea supplier UUID" }, { key: "profile_id", description: "Omnea profile UUID" } ],
    bodyParams: [ { key: "accountName", type: "string", description: "Account name" }, { key: "accountNumber", type: "string", description: "Account number" }, { key: "iban", type: "string", description: "IBAN" }, { key: "swiftCode", type: "string", description: "SWIFT/BIC code" }, { key: "sortCode", type: "string", description: "Sort code" }, { key: "bankName", type: "string", description: "Bank name" }, { key: "currency", type: "object", description: "Currency object (code)" }, { key: "address", type: "object", description: "Bank address object" } ],
  },
  {
    id: "delete-bank-account",
    name: "Unlink bank account",
    method: "DELETE",
    path: "{{baseUrl}}/v1/suppliers/{{supplier_id}}/profiles/{{profile_id}}/bank-accounts/{{bank_account_id}}",
    description: "Unlink / remove a bank account from a supplier profile.",
    collection: "Bank Account",
    auth: "Bearer {{accessToken}}",
    pathParams: [ { key: "supplier_id", description: "Omnea supplier UUID" }, { key: "profile_id", description: "Omnea profile UUID" }, { key: "bank_account_id", description: "Omnea bank account UUID" } ],
  },
  {
    id: "list-all-bank-accounts-for-supplier",
    name: "List all bank accounts for supplier",
    method: "GET",
    path: "{{baseUrl}}/v1/suppliers/{{supplier_id}}/bank-accounts",
    description: "List all bank accounts across all profiles for a supplier.",
    collection: "Bank Account",
    auth: "Bearer {{accessToken}}",
    pathParams: [ { key: "supplier_id", description: "Omnea supplier UUID" } ],
  },
  {
    id: "list-bank-accounts-by-remote-id",
    name: "List bank accounts by supplier remote ID",
    method: "GET",
    path: "{{baseUrl}}/v1/by-remote-id/suppliers/{{remoteId}}/bank-accounts",
    description: "List bank accounts by supplier remote ID (BC Vendor No)",
    collection: "Bank Account",
    auth: "Bearer {{accessToken}}",
    pathParams: [ { key: "remoteId", description: "BC Vendor No (remoteId)" } ],
  },
  {
    id: "list-bank-accounts-by-remote-profile-id",
    name: "List bank accounts by supplier + subsidiary remote IDs",
    method: "GET",
    path: "{{baseUrl}}/v1/by-remote-id/suppliers/{{remoteId}}/profiles/{{subRemoteId}}/bank-accounts",
    description: "List bank accounts by supplier + subsidiary remote IDs.",
    collection: "Bank Account",
    auth: "Bearer {{accessToken}}",
    pathParams: [ { key: "remoteId", description: "BC Vendor No (remoteId)" }, { key: "subRemoteId", description: "BC Subsidiary Remote ID" } ],
  },
  {
    id: "link-bank-accounts-by-remote-ids",
    name: "Link bank accounts by remote IDs",
    method: "POST",
    path: "{{baseUrl}}/v1/by-remote-id/suppliers/{{remoteId}}/profiles/{{subRemoteId}}/bank-accounts",
    description: "Link bank accounts by remote IDs.",
    collection: "Bank Account",
    auth: "Bearer {{accessToken}}",
    pathParams: [ { key: "remoteId", description: "BC Vendor No (remoteId)" }, { key: "subRemoteId", description: "BC Subsidiary Remote ID" } ],
    bodyParams: [ { key: "bankAccounts", type: "array", description: "Array of bank accounts to link", required: true } ],
  },
  {
    id: "unlink-bank-account-by-remote-ids",
    name: "Unlink bank account by remote IDs",
    method: "DELETE",
    path: "{{baseUrl}}/v1/by-remote-id/suppliers/{{remoteId}}/profiles/{{subRemoteId}}/bank-accounts/{{bankId}}",
    description: "Unlink bank account by remote IDs.",
    collection: "Bank Account",
    auth: "Bearer {{accessToken}}",
    pathParams: [ { key: "remoteId", description: "BC Vendor No (remoteId)" }, { key: "subRemoteId", description: "BC Subsidiary Remote ID" }, { key: "bankId", description: "Bank account ID" } ],
  },

  // Payment Terms
  {
    id: "list-payment-terms",
    name: "List payment terms",
    method: "GET",
    path: "{{baseUrl}}/v1/payment-terms",
    description: "List all payment terms (paginated).",
    collection: "Payment Terms",
    auth: "Bearer {{accessToken}}",
    pathParams: [],
  },
  {
    id: "get-payment-term-by-id",
    name: "Get payment term by ID",
    method: "GET",
    path: "{{baseUrl}}/v1/payment-terms/{{paymentTermId}}",
    description: "Get payment term by UUID.",
    collection: "Payment Terms",
    auth: "Bearer {{accessToken}}",
    pathParams: [ { key: "paymentTermId", description: "Payment term UUID" } ],
  },

  // Currencies
  {
    id: "list-currencies",
    name: "List currencies",
    method: "GET",
    path: "{{baseUrl}}/v1/currencies",
    description: "Get a paginated list of currencies.",
    collection: "Currencies",
    auth: "Bearer {{accessToken}}",
    pathParams: [
      { key: "limit", description: "Query param: 1-100 (default: 100)" },
      { key: "cursor", description: "Query param: pagination cursor" },
      { key: "sort", description: "Query param: name|-name|createdAt|-createdAt|updatedAt|-updatedAt" },
      { key: "filter", description: "Query param: OData filter (URL encoded)" },
    ],
  },
  {
    id: "get-currency-by-id",
    name: "Get currency by ID",
    method: "GET",
    path: "{{baseUrl}}/v1/currencies/{{currencyId}}",
    description: "Get currency by UUID.",
    collection: "Currencies",
    auth: "Bearer {{accessToken}}",
    pathParams: [ { key: "currencyId", description: "Currency UUID" } ],
  },
  {
    id: "get-currency-by-remote-id",
    name: "Get currency by remote ID",
    method: "GET",
    path: "{{baseUrl}}/v1/by-remote-id/currencies/{{remoteId}}",
    description: "Get a currency by remote ID.",
    collection: "Currencies",
    auth: "Bearer {{accessToken}}",
    pathParams: [ { key: "remoteId", description: "Remote ID of the currency (URL encoded)" } ],
  },
  {
    id: "create-currencies-batch",
    name: "Create currencies",
    method: "POST",
    path: "{{baseUrl}}/v1/currencies/batch",
    description: "Create new currencies.",
    collection: "Currencies",
    auth: "Bearer {{accessToken}}",
    pathParams: [],
    bodyParams: [
      { key: "currencies", type: "array", description: "Array of currencies to create (1-100 items)", required: true },
      { key: "currencies[].name", type: "string", description: "Name of the currency", required: true },
      { key: "currencies[].code", type: "string", description: "3-letter currency code (ISO 4217), uppercase", required: true },
      { key: "currencies[].fxRate", type: "number", description: "Exchange rate relative to base currency", required: true },
      { key: "currencies[].displaySymbol", type: "string", description: "Display symbol for the currency" },
      { key: "currencies[].isVisible", type: "boolean", description: "Whether the currency is visible to users" },
      { key: "currencies[].remoteId", type: "string", description: "External system identifier", required: true },
      { key: "currencies[].dependsOn", type: "object", description: "Optional dependsOn object" },
    ],
  },
  {
    id: "update-currency-by-id",
    name: "Update a currency",
    method: "PATCH",
    path: "{{baseUrl}}/v1/currencies/{{currencyId}}",
    description: "Update an existing currency.",
    collection: "Currencies",
    auth: "Bearer {{accessToken}}",
    pathParams: [ { key: "currencyId", description: "UUID of the currency to update" } ],
    bodyParams: [
      { key: "name", type: "string", description: "Name of the currency" },
      { key: "code", type: "string", description: "3-letter currency code (ISO 4217), uppercase" },
      { key: "fxRate", type: "number", description: "Exchange rate relative to base currency" },
      { key: "displaySymbol", type: "string", description: "Display symbol for the currency" },
      { key: "isVisible", type: "boolean", description: "Whether the currency is visible to users" },
      { key: "remoteId", type: "string", description: "External system identifier" },
      { key: "isArchived", type: "boolean", description: "Whether the currency is archived" },
      { key: "dependsOn", type: "object", description: "Optional dependsOn object" },
    ],
  },
  {
    id: "update-currency-by-remote-id",
    name: "Update a currency by remote ID",
    method: "PATCH",
    path: "{{baseUrl}}/v1/by-remote-id/currencies/{{remoteId}}",
    description: "Update a currency by remote ID.",
    collection: "Currencies",
    auth: "Bearer {{accessToken}}",
    pathParams: [ { key: "remoteId", description: "Remote ID of the currency to update (URL encoded)" } ],
    bodyParams: [
      { key: "name", type: "string", description: "Name of the currency" },
      { key: "code", type: "string", description: "3-letter currency code (ISO 4217), uppercase" },
      { key: "fxRate", type: "number", description: "Exchange rate relative to base currency" },
      { key: "displaySymbol", type: "string", description: "Display symbol for the currency" },
      { key: "isVisible", type: "boolean", description: "Whether the currency is visible to users" },
      { key: "isArchived", type: "boolean", description: "Whether the currency is archived" },
      { key: "dependsOn", type: "object", description: "Optional dependsOn object" },
    ],
  },

  // Payment Methods
  {
    id: "list-payment-methods",
    name: "List payment methods",
    method: "GET",
    path: "{{baseUrl}}/v1/payment-methods",
    description: "List all payment methods.",
    collection: "Payment Methods",
    auth: "Bearer {{accessToken}}",
    pathParams: [],
  },
  {
    id: "get-payment-method-by-id",
    name: "Get payment method by ID",
    method: "GET",
    path: "{{baseUrl}}/v1/payment-methods/{{paymentMethodId}}",
    description: "Get payment method by UUID.",
    collection: "Payment Methods",
    auth: "Bearer {{accessToken}}",
    pathParams: [ { key: "paymentMethodId", description: "Payment method UUID" } ],
  },

  // Addresses
  {
    id: "list-addresses",
    name: "List addresses",
    method: "GET",
    path: "{{baseUrl}}/v1/addresses",
    description: "List addresses.",
    collection: "Addresses",
    auth: "Bearer {{accessToken}}",
    pathParams: [],
  },
  {
    id: "get-address-by-id",
    name: "Get address by ID",
    method: "GET",
    path: "{{baseUrl}}/v1/addresses/{{addressId}}",
    description: "Get address by UUID.",
    collection: "Addresses",
    auth: "Bearer {{accessToken}}",
    pathParams: [ { key: "addressId", description: "Address UUID" } ],
  },

  // Line Item Types
  {
    id: "list-line-item-types",
    name: "List line item types",
    method: "GET",
    path: "{{baseUrl}}/v1/line-item-types",
    description: "List all line item types available in the Omnea instance.",
    collection: "Line Item Types",
    auth: "Bearer {{accessToken}}",
    pathParams: [],
  },

  // Dependencies
  {
    id: "list-dependencies",
    name: "List dependencies",
    method: "GET",
    path: "{{baseUrl}}/v1/dependencies",
    description: "List all dependency objects (used in departments, custom data, etc. to link records).",
    collection: "Dependencies",
    auth: "Bearer {{accessToken}}",
    pathParams: [],
  },

  // Purchase Orders
  {
    id: "list-purchase-orders",
    name: "List purchase orders",
    method: "GET",
    path: "{{baseUrl}}/v1/purchase-orders",
    description: "List purchase orders (paginated).",
    collection: "Purchase Orders",
    auth: "Bearer {{accessToken}}",
    pathParams: [],
  },
  {
    id: "get-purchase-order-by-id",
    name: "Get purchase order by ID",
    method: "GET",
    path: "{{baseUrl}}/v1/purchase-orders/{{purchaseOrderId}}",
    description: "Get purchase order by UUID.",
    collection: "Purchase Orders",
    auth: "Bearer {{accessToken}}",
    pathParams: [ { key: "purchaseOrderId", description: "Purchase order UUID" } ],
  },
];

// Field mappings for both integration directions
export interface FieldMapping {
  omneaField: string;
  omneaApiPath: string;
  bcField: string;
  bcTableRef: string;
  direction: "omnea-to-bc" | "bc-to-omnea" | "bidirectional";
  entity: "Supplier" | "Profile" | "Bank Account";
  required?: boolean;
  notes?: string;
}

export const fieldMappings: FieldMapping[] = [
  // Supplier-level fields
  { omneaField: "Name", omneaApiPath: "name", bcField: "Name", bcTableRef: "Table 23, Field 2", direction: "bidirectional", entity: "Supplier", required: true },
  { omneaField: "Legal Name", omneaApiPath: "legalName", bcField: "Name", bcTableRef: "Table 23, Field 2", direction: "bc-to-omnea", entity: "Supplier", required: true },
  { omneaField: "Tax Number", omneaApiPath: "taxNumber", bcField: "VAT Registration No.", bcTableRef: "Table 23, Field 86", direction: "bidirectional", entity: "Supplier", required: true, notes: "Primary identity anchor" },
  { omneaField: "Remote ID", omneaApiPath: "remoteId", bcField: "Vendor No.", bcTableRef: "Table 23, Field 1", direction: "omnea-to-bc", entity: "Supplier", required: true, notes: "BC Vendor No written back to Omnea" },
  { omneaField: "Remote Link", omneaApiPath: "remoteLink", bcField: "Vendor Card URL", bcTableRef: "N/A (computed)", direction: "omnea-to-bc", entity: "Supplier" },
  { omneaField: "State", omneaApiPath: "state", bcField: "Blocked", bcTableRef: "Table 23, Field 39", direction: "bidirectional", entity: "Supplier", notes: "active→Blank, pending→Payment, archived→All" },
  { omneaField: "Website", omneaApiPath: "website", bcField: "Home Page", bcTableRef: "Table 23, Field 54", direction: "bidirectional", entity: "Supplier" },
  { omneaField: "Description", omneaApiPath: "description", bcField: "—", bcTableRef: "N/A", direction: "bc-to-omnea", entity: "Supplier" },
  { omneaField: "Is Preferred", omneaApiPath: "isPreferred", bcField: "—", bcTableRef: "N/A", direction: "bc-to-omnea", entity: "Supplier" },
  // Address fields
  { omneaField: "Address Street", omneaApiPath: "address.street1", bcField: "Address", bcTableRef: "Table 23, Field 5", direction: "bidirectional", entity: "Supplier" },
  { omneaField: "Address Street 2", omneaApiPath: "address.street2", bcField: "Address 2", bcTableRef: "Table 23, Field 6", direction: "bidirectional", entity: "Supplier" },
  { omneaField: "City", omneaApiPath: "address.city", bcField: "City", bcTableRef: "Table 23, Field 7", direction: "bidirectional", entity: "Supplier" },
  { omneaField: "State/County", omneaApiPath: "address.state", bcField: "County", bcTableRef: "Table 23, Field 92", direction: "bidirectional", entity: "Supplier" },
  { omneaField: "Zip Code", omneaApiPath: "address.zipCode", bcField: "Post Code", bcTableRef: "Table 23, Field 91", direction: "bidirectional", entity: "Supplier" },
  { omneaField: "Country", omneaApiPath: "address.country", bcField: "Country/Region Code", bcTableRef: "Table 23, Field 35", direction: "bidirectional", entity: "Supplier" },
  // Custom fields
  { omneaField: "Corporate Reg Number", omneaApiPath: "customFields.corporate-registration-number.value", bcField: "Registration No.", bcTableRef: "Table 23, Field 25", direction: "bidirectional", entity: "Supplier", notes: "Secondary identity anchor" },
  { omneaField: "Entity Type", omneaApiPath: "customFields.entity-type.value.name", bcField: "Gen. Bus. Posting Group", bcTableRef: "Table 23, Field 88", direction: "bidirectional", entity: "Supplier" },
  { omneaField: "Materiality Level", omneaApiPath: "customFields.materiality-level.value.name", bcField: "—", bcTableRef: "N/A", direction: "bc-to-omnea", entity: "Supplier", notes: "Governance field" },
  { omneaField: "InfoSec Criticality", omneaApiPath: "customFields.infosec-criticality-tier.value.name", bcField: "—", bcTableRef: "N/A", direction: "bc-to-omnea", entity: "Supplier", notes: "Governance field" },
  { omneaField: "InfoSec Sensitivity", omneaApiPath: "customFields.infosec-sensitivity-tier.value.name", bcField: "—", bcTableRef: "N/A", direction: "bc-to-omnea", entity: "Supplier", notes: "Governance field" },
  { omneaField: "CS Materiality Status", omneaApiPath: "customFields.cs-service-materiality-status.value", bcField: "—", bcTableRef: "N/A", direction: "bc-to-omnea", entity: "Supplier", notes: "Risk blocking logic" },
  { omneaField: "KYC Materiality Status", omneaApiPath: "customFields.kyc-materiality-status.value", bcField: "—", bcTableRef: "N/A", direction: "bc-to-omnea", entity: "Supplier", notes: "Risk blocking logic" },
  { omneaField: "SCA Materiality Status", omneaApiPath: "customFields.sca-materiality-status.value", bcField: "—", bcTableRef: "N/A", direction: "bc-to-omnea", entity: "Supplier", notes: "Risk blocking logic" },
  // Profile-level fields
  { omneaField: "Profile ID", omneaApiPath: "data[n].id", bcField: "—", bcTableRef: "N/A", direction: "bc-to-omnea", entity: "Profile" },
  { omneaField: "Profile State", omneaApiPath: "data[n].state", bcField: "Blocked", bcTableRef: "Table 23, Field 39", direction: "bidirectional", entity: "Profile" },
  { omneaField: "Subsidiary Name", omneaApiPath: "data[n].subsidiary.name", bcField: "Legal Entity", bcTableRef: "N/A (Company)", direction: "bidirectional", entity: "Profile" },
  { omneaField: "Subsidiary Remote ID", omneaApiPath: "data[n].subsidiary.remoteId", bcField: "Company Code", bcTableRef: "N/A", direction: "omnea-to-bc", entity: "Profile" },
  { omneaField: "Payment Method", omneaApiPath: "data[n].paymentMethod.name", bcField: "Payment Method Code", bcTableRef: "Table 23, Field 287", direction: "bidirectional", entity: "Profile" },
  { omneaField: "Payment Terms", omneaApiPath: "data[n].paymentTerms.name", bcField: "Payment Terms Code", bcTableRef: "Table 23, Field 27", direction: "bidirectional", entity: "Profile", required: true },
  { omneaField: "Relationship Owner", omneaApiPath: "customFields.supplierProfileRelationshipOwner.value.email", bcField: "Purchaser Code", bcTableRef: "Table 23, Field 29", direction: "bidirectional", entity: "Profile", notes: "SSO email → Medius routing" },
  { omneaField: "Profile Remote ID", omneaApiPath: "remoteId", bcField: "Vendor No.", bcTableRef: "Table 23, Field 1", direction: "omnea-to-bc", entity: "Profile", required: true },
  { omneaField: "Profile Remote Link", omneaApiPath: "remoteLink", bcField: "Vendor Card URL", bcTableRef: "N/A", direction: "omnea-to-bc", entity: "Profile" },
  // Bank Account fields
  { omneaField: "Account Name", omneaApiPath: "accountName", bcField: "Name", bcTableRef: "Table 287, Field 2", direction: "bidirectional", entity: "Bank Account" },
  { omneaField: "Bank Name", omneaApiPath: "bankName", bcField: "Bank Name", bcTableRef: "Table 287, Field 3", direction: "bidirectional", entity: "Bank Account" },
  { omneaField: "Account Number", omneaApiPath: "accountNumber", bcField: "Bank Account No.", bcTableRef: "Table 287, Field 4", direction: "bidirectional", entity: "Bank Account" },
  { omneaField: "Sort Code", omneaApiPath: "sortCode", bcField: "Bank Branch No.", bcTableRef: "Table 287, Field 12", direction: "bidirectional", entity: "Bank Account" },
  { omneaField: "IBAN", omneaApiPath: "iban", bcField: "IBAN", bcTableRef: "Table 287, Field 23", direction: "bidirectional", entity: "Bank Account", required: true },
  { omneaField: "SWIFT/BIC Code", omneaApiPath: "swiftCode", bcField: "SWIFT Code", bcTableRef: "Table 287, Field 24", direction: "bidirectional", entity: "Bank Account" },
  { omneaField: "Currency Code", omneaApiPath: "currency.code", bcField: "Currency Code", bcTableRef: "Table 287, Field 9", direction: "bidirectional", entity: "Bank Account" },
  { omneaField: "Is Active", omneaApiPath: "isActive", bcField: "—", bcTableRef: "N/A", direction: "bc-to-omnea", entity: "Bank Account" },
  { omneaField: "Bank Remote ID", omneaApiPath: "remoteId", bcField: "Bank Code", bcTableRef: "Table 287, Field 1", direction: "omnea-to-bc", entity: "Bank Account", required: true, notes: "BC Bank Code written back" },
  { omneaField: "Bank Address", omneaApiPath: "address.street1", bcField: "Address", bcTableRef: "Table 287, Field 5", direction: "bidirectional", entity: "Bank Account" },
  { omneaField: "Bank City", omneaApiPath: "address.city", bcField: "City", bcTableRef: "Table 287, Field 7", direction: "bidirectional", entity: "Bank Account" },
  { omneaField: "Bank Country", omneaApiPath: "address.country", bcField: "Country/Region Code", bcTableRef: "Table 287, Field 35", direction: "bidirectional", entity: "Bank Account" },
];

// Simulation steps matching Postman collection runner
export interface SimulationStep {
  id: string;
  order: number;
  name: string;
  method: "GET" | "POST" | "PATCH";
  endpointId: string;
  description: string;
  dependsOn?: string;
  outputVars?: string[];
}

export const simulationSteps: SimulationStep[] = [
  { id: "step-1", order: 1, name: "Authenticate", method: "POST", endpointId: "auth-token", description: "Get OAuth access token", outputVars: ["accessToken"] },
  { id: "step-2", order: 2, name: "Get Suppliers", method: "GET", endpointId: "get-suppliers", description: "List suppliers, capture first supplier ID", dependsOn: "step-1", outputVars: ["active_supplier_id"] },
  { id: "step-3", order: 3, name: "Get Supplier Details", method: "GET", endpointId: "get-supplier-by-id", description: "Fetch full supplier with custom fields", dependsOn: "step-2", outputVars: ["supplier_name_context"] },
  { id: "step-4", order: 4, name: "Get Profiles", method: "GET", endpointId: "get-profiles-by-supplier", description: "List subsidiary profiles for the supplier", dependsOn: "step-3", outputVars: ["active_profile_id"] },
  { id: "step-5", order: 5, name: "Get Bank Accounts", method: "GET", endpointId: "list-bank-accounts", description: "List bank accounts for the selected profile", dependsOn: "step-4", outputVars: ["bank_account_id"] },
  { id: "step-6", order: 6, name: "PATCH Profile (Handshake)", method: "PATCH", endpointId: "update-profile", description: "Write remoteId + remoteLink back to Omnea", dependsOn: "step-4" },
  { id: "step-7", order: 7, name: "PATCH Bank Account", method: "PATCH", endpointId: "update-bank-account", description: "Write BC Bank Code to Omnea bank account", dependsOn: "step-5" },
];
