// Audit page mock data: suppliers with materiality tags and requests

export interface AuditSupplier {
  id: string;
  publicId: string;
  name: string;
  legalName: string;
  state: string;
  entityType: string;
  materialityLevel: string;
  materialitySubstitutability: string;
  infosecCriticalityTier: string;
  infosecSensitivityTier: string;
  servicingEntities: string[];
  cifsSupported: string[];
  tags: string[];
}

export interface AuditRequest {
  requestUUID: string;
  requestId: string;
  name: string;
  supplier: string;
  workflow: string;
  state: string;
  stage: string;
  type: string;
  priority: string;
  tags: string[];
  createdOn: string;
  dueDate: string;
  assignees: string;
  materialityLevel: string;
  infosecCriticality: string;
  infosecSensitivity: string;
}

// All known materiality tag values for filtering
export const materialityTagOptions: string[] = [
  "Materiality Substitutability = Easy",
  "Materiality Substitutability = Instant Replacement",
  "Materiality Impact = Low",
  "Materiality Impact = Medium",
  "Materiality Impact = High",
  "Banking Supplier",
  "Other types of non-public data = TRUE",
  "Data Processed = TRUE",
  "PII Processed = TRUE",
  "BSP - Market Tier 1",
  "BSP - Market Tier 2",
  "Tier B (BP)",
  "Tier C (BP)",
  "Criticality = Tier 1",
  "Criticality = Tier 2",
  "Criticality = Tier 3",
];

export const auditSuppliers: AuditSupplier[] = [
  {
    id: "9b044392-3d3c-4552-b8bc-1a6070127911",
    publicId: "S-2918",
    name: "Banco BICE",
    legalName: "Banco BICE",
    state: "active",
    entityType: "Banking Services",
    materialityLevel: "Non material",
    materialitySubstitutability: "Easy",
    infosecCriticalityTier: "3",
    infosecSensitivityTier: "B",
    servicingEntities: ["Wise Chile SpA"],
    cifsSupported: [],
    tags: [
      "Materiality Substitutability = Easy",
      "Banking Supplier",
      "Other types of non-public data = TRUE",
      "Data Processed = TRUE",
      "Tier C (BP)",
      "PII Processed = TRUE",
      "BSP - Market Tier 1",
    ],
  },
  {
    id: "a1b2c3d4-5e6f-7890-abcd-ef1234567890",
    publicId: "S-3102",
    name: "CloudPay Solutions",
    legalName: "CloudPay Solutions Ltd",
    state: "active",
    entityType: "Payment Services",
    materialityLevel: "Material",
    materialitySubstitutability: "Instant Replacement",
    infosecCriticalityTier: "1",
    infosecSensitivityTier: "A",
    servicingEntities: ["Wise Payments Ltd", "Wise Europe SA"],
    cifsSupported: ["CIF-001", "CIF-002"],
    tags: [
      "Materiality Substitutability = Instant Replacement",
      "Banking Supplier",
      "Other types of non-public data = TRUE",
      "Data Processed = TRUE",
      "Tier C (BP)",
      "BSP - Market Tier 1",
      "Materiality Impact = Low",
    ],
  },
  {
    id: "b2c3d4e5-6f78-90ab-cdef-123456789012",
    publicId: "S-2847",
    name: "Nordic KYC Services",
    legalName: "Nordic KYC Services AB",
    state: "active",
    entityType: "Compliance Services",
    materialityLevel: "Material",
    materialitySubstitutability: "Easy",
    infosecCriticalityTier: "2",
    infosecSensitivityTier: "A",
    servicingEntities: ["Wise Payments Ltd"],
    cifsSupported: ["CIF-003"],
    tags: [
      "Materiality Substitutability = Easy",
      "Tier B (BP)",
      "Banking Supplier",
      "Data Processed = TRUE",
      "PII Processed = TRUE",
      "BSP - Market Tier 1",
      "Criticality = Tier 2",
    ],
  },
  {
    id: "c3d4e5f6-7890-abcd-ef12-345678901234",
    publicId: "S-3455",
    name: "DataGuard Analytics",
    legalName: "DataGuard Analytics GmbH",
    state: "active",
    entityType: "Technology Services",
    materialityLevel: "Non material",
    materialitySubstitutability: "Easy",
    infosecCriticalityTier: "3",
    infosecSensitivityTier: "C",
    servicingEntities: ["Wise Europe SA"],
    cifsSupported: [],
    tags: [
      "Materiality Substitutability = Easy",
      "Data Processed = TRUE",
      "BSP - Market Tier 2",
      "Criticality = Tier 3",
    ],
  },
  {
    id: "d4e5f678-90ab-cdef-1234-567890123456",
    publicId: "S-2590",
    name: "SecureVault Inc",
    legalName: "SecureVault Inc.",
    state: "active",
    entityType: "Banking Services",
    materialityLevel: "Material",
    materialitySubstitutability: "Instant Replacement",
    infosecCriticalityTier: "1",
    infosecSensitivityTier: "A",
    servicingEntities: ["Wise US Inc", "Wise Payments Ltd"],
    cifsSupported: ["CIF-001"],
    tags: [
      "Materiality Substitutability = Instant Replacement",
      "Banking Supplier",
      "Other types of non-public data = TRUE",
      "Data Processed = TRUE",
      "PII Processed = TRUE",
      "BSP - Market Tier 1",
      "Materiality Impact = High",
      "Criticality = Tier 1",
    ],
  },
  {
    id: "e5f67890-abcd-ef12-3456-789012345678",
    publicId: "S-4001",
    name: "RegTech Compliance",
    legalName: "RegTech Compliance Pty Ltd",
    state: "pending",
    entityType: "Compliance Services",
    materialityLevel: "Non material",
    materialitySubstitutability: "Easy",
    infosecCriticalityTier: "2",
    infosecSensitivityTier: "B",
    servicingEntities: ["Wise Australia Pty Ltd"],
    cifsSupported: [],
    tags: [
      "Materiality Substitutability = Easy",
      "Data Processed = TRUE",
      "Tier B (BP)",
      "BSP - Market Tier 2",
      "Criticality = Tier 2",
    ],
  },
];

export const auditRequests: AuditRequest[] = [
  {
    requestUUID: "req-001-uuid",
    requestId: "REQ-5521",
    name: "Annual Security Assessment",
    supplier: "Banco BICE",
    workflow: "Baseline Assessment",
    state: "In Progress",
    stage: "Supplier Review",
    type: "Assessment",
    priority: "High",
    tags: [
      "Materiality Substitutability = Easy",
      "Banking Supplier",
      "Other types of non-public data = TRUE",
      "Data Processed = TRUE",
      "Tier C (BP)",
      "PII Processed = TRUE",
      "BSP - Market Tier 1",
    ],
    createdOn: "2025-11-15",
    dueDate: "2026-04-15",
    assignees: "Maria Johansson",
    materialityLevel: "Non material",
    infosecCriticality: "3",
    infosecSensitivity: "B",
  },
  {
    requestUUID: "req-002-uuid",
    requestId: "REQ-5522",
    name: "KYC Due Diligence Review",
    supplier: "Banco BICE",
    workflow: "KYC Assessment",
    state: "Pending",
    stage: "Internal Review",
    type: "Due Diligence",
    priority: "Medium",
    tags: [
      "Materiality Substitutability = Easy",
      "Banking Supplier",
      "PII Processed = TRUE",
      "BSP - Market Tier 1",
    ],
    createdOn: "2026-01-10",
    dueDate: "2026-05-10",
    assignees: "Erik Lindström",
    materialityLevel: "Non material",
    infosecCriticality: "3",
    infosecSensitivity: "B",
  },
  {
    requestUUID: "req-003-uuid",
    requestId: "REQ-5610",
    name: "Onboarding Security Review",
    supplier: "CloudPay Solutions",
    workflow: "Standard Assessment",
    state: "In Progress",
    stage: "Vendor Questionnaire",
    type: "Assessment",
    priority: "Critical",
    tags: [
      "Materiality Substitutability = Instant Replacement",
      "Banking Supplier",
      "Other types of non-public data = TRUE",
      "Data Processed = TRUE",
      "Tier C (BP)",
      "BSP - Market Tier 1",
      "Materiality Impact = Low",
    ],
    createdOn: "2026-02-01",
    dueDate: "2026-06-01",
    assignees: "Anna Virtanen",
    materialityLevel: "Material",
    infosecCriticality: "1",
    infosecSensitivity: "A",
  },
  {
    requestUUID: "req-004-uuid",
    requestId: "REQ-5611",
    name: "Identity & Access Management Survey",
    supplier: "Nordic KYC Services",
    workflow: "IAM Assessment",
    state: "Completed",
    stage: "Closed",
    type: "Survey",
    priority: "Medium",
    tags: [
      "Materiality Substitutability = Easy",
      "Tier B (BP)",
      "Banking Supplier",
      "Data Processed = TRUE",
      "PII Processed = TRUE",
      "BSP - Market Tier 1",
      "Criticality = Tier 2",
    ],
    createdOn: "2025-09-20",
    dueDate: "2026-01-20",
    assignees: "Tomislav Kovač",
    materialityLevel: "Material",
    infosecCriticality: "2",
    infosecSensitivity: "A",
  },
  {
    requestUUID: "req-005-uuid",
    requestId: "REQ-5700",
    name: "Data Processing Impact Assessment",
    supplier: "DataGuard Analytics",
    workflow: "DPIA",
    state: "In Progress",
    stage: "Risk Analysis",
    type: "Assessment",
    priority: "Low",
    tags: [
      "Materiality Substitutability = Easy",
      "Data Processed = TRUE",
      "BSP - Market Tier 2",
      "Criticality = Tier 3",
    ],
    createdOn: "2026-01-25",
    dueDate: "2026-07-25",
    assignees: "Maria Johansson",
    materialityLevel: "Non material",
    infosecCriticality: "3",
    infosecSensitivity: "C",
  },
  {
    requestUUID: "req-006-uuid",
    requestId: "REQ-5701",
    name: "Penetration Test Review",
    supplier: "SecureVault Inc",
    workflow: "Security Assessment",
    state: "In Progress",
    stage: "Evidence Collection",
    type: "Assessment",
    priority: "Critical",
    tags: [
      "Materiality Substitutability = Instant Replacement",
      "Banking Supplier",
      "Other types of non-public data = TRUE",
      "Data Processed = TRUE",
      "PII Processed = TRUE",
      "BSP - Market Tier 1",
      "Materiality Impact = High",
      "Criticality = Tier 1",
    ],
    createdOn: "2026-02-10",
    dueDate: "2026-05-10",
    assignees: "Erik Lindström",
    materialityLevel: "Material",
    infosecCriticality: "1",
    infosecSensitivity: "A",
  },
  {
    requestUUID: "req-007-uuid",
    requestId: "REQ-5702",
    name: "SCA Compliance Check",
    supplier: "SecureVault Inc",
    workflow: "SCA Assessment",
    state: "Pending",
    stage: "Awaiting Supplier",
    type: "Compliance",
    priority: "High",
    tags: [
      "Materiality Substitutability = Instant Replacement",
      "Banking Supplier",
      "PII Processed = TRUE",
      "BSP - Market Tier 1",
      "Criticality = Tier 1",
    ],
    createdOn: "2026-03-01",
    dueDate: "2026-06-01",
    assignees: "Anna Virtanen",
    materialityLevel: "Material",
    infosecCriticality: "1",
    infosecSensitivity: "A",
  },
  {
    requestUUID: "req-008-uuid",
    requestId: "REQ-5800",
    name: "Vendor Risk Assessment",
    supplier: "RegTech Compliance",
    workflow: "Risk Assessment",
    state: "In Progress",
    stage: "Questionnaire Sent",
    type: "Assessment",
    priority: "Medium",
    tags: [
      "Materiality Substitutability = Easy",
      "Data Processed = TRUE",
      "Tier B (BP)",
      "BSP - Market Tier 2",
      "Criticality = Tier 2",
    ],
    createdOn: "2026-02-20",
    dueDate: "2026-08-20",
    assignees: "Tomislav Kovač",
    materialityLevel: "Non material",
    infosecCriticality: "2",
    infosecSensitivity: "B",
  },
];
