// Audit page mock data: suppliers with materiality tags and requests

export interface AuditSupplier {
  id: string;
  publicId: string;
  name: string;
  legalName: string;
  state: string;
  entityType: string;
  materialityLevel: string;
  materialityImpact?: string;
  materialitySubstitutability: string;
  cif?: boolean;
  thirdPartySupplier?: boolean;
  supportive?: boolean;
  bankingSupplier?: boolean;
  bspMarketTier?: string;
  outsourcing?: string;
  customerPiiProcessed?: boolean;
  mainAssessmentBankingQuestion7?: string;
  contractingParty?: string;
  lightTouchSupplier?: boolean;
  infosecCriticalityTier: string;
  infosecSensitivityTier: string;
  servicingEntities: string[];
  cifsSupported: string[];
  tags: string[];
}

export interface AuditRequest {
  requestUUID: string;
  requestId: string;
  name: string;
  supplier: string;
  workflow: string;
  state: string;
  stage: string;
  type: string;
  priority: string;
  tags: string[];
  createdOn: string;
  dueDate: string;
  assignees: string;
  materialityLevel: string;
  infosecCriticality: string;
  infosecSensitivity: string;
  questions: Record<string, string>;
}

// All known tag values for filtering
export const materialityTagOptions: string[] = [
  "Materiality Substitutability = Easy",
  "Materiality Substitutability = Instant Replacement",
  "Materiality Substitutability = Difficult",
  "Materiality Substitutability = Impossible",
  "Materiality Impact = Low",
  "Materiality Impact = Medium",
  "Materiality Impact = High",
  "Banking Supplier",
  "Third Party Supplier = TRUE",
  "CIF = TRUE",
  "SUPPORTIVE = TRUE",
  "Other types of non-public data = TRUE",
  "Data Processed = TRUE",
  "PII Processed = TRUE",
  "BSP - Market Tier 1",
  "BSP - Market Tier 2",
  "BSP - Market Tier 3",
  "Tier B (BP)",
  "Tier C (BP)",
  "Criticality = Tier 1",
  "Criticality = Tier 2",
  "Criticality = Tier 3",
];

export const auditSuppliers: AuditSupplier[] = [
  {
    id: "9b044392-3d3c-4552-b8bc-1a6070127911",
    publicId: "S-2918",
    name: "Banco BICE",
    legalName: "Banco BICE",
    state: "active",
    entityType: "Banking Services",
    materialityLevel: "Non material",
    materialitySubstitutability: "Easy",
    infosecCriticalityTier: "3",
    infosecSensitivityTier: "B",
    servicingEntities: ["Wise Chile SpA"],
    cifsSupported: [],
    tags: [
      "Materiality Substitutability = Easy",
      "Materiality Impact = Low",
      "Banking Supplier",
      "Other types of non-public data = TRUE",
      "Data Processed = TRUE",
      "Tier C (BP)",
      "PII Processed = TRUE",
      "BSP - Market Tier 1",
    ],
  },
  {
    id: "a1b2c3d4-5e6f-7890-abcd-ef1234567890",
    publicId: "S-3102",
    name: "CloudPay Solutions",
    legalName: "CloudPay Solutions Ltd",
    state: "active",
    entityType: "Payment Services",
    materialityLevel: "Material",
    materialitySubstitutability: "Difficult",
    infosecCriticalityTier: "1",
    infosecSensitivityTier: "A",
    servicingEntities: ["Wise Payments Ltd", "Wise Europe SA"],
    cifsSupported: ["CIF-001", "CIF-002"],
    tags: [
      "Materiality Impact = High",
      "Materiality Substitutability = Difficult",
      "Banking Supplier",
      "BSP - Market Tier 1",
      "Other types of non-public data = TRUE",
      "Data Processed = TRUE",
      "Tier C (BP)",
    ],
  },
  {
    id: "b2c3d4e5-6f78-90ab-cdef-123456789012",
    publicId: "S-2847",
    name: "Nordic KYC Services",
    legalName: "Nordic KYC Services AB",
    state: "active",
    entityType: "Compliance Services",
    materialityLevel: "Non material",
    materialitySubstitutability: "Easy",
    infosecCriticalityTier: "2",
    infosecSensitivityTier: "A",
    servicingEntities: ["Wise Payments Ltd"],
    cifsSupported: ["CIF-003"],
    tags: [
      "Materiality Impact = Low",
      "Materiality Substitutability = Easy",
      "CIF = TRUE",
      "Third Party Supplier = TRUE",
      "Tier B (BP)",
      "Data Processed = TRUE",
      "PII Processed = TRUE",
      "BSP - Market Tier 1",
      "Criticality = Tier 2",
    ],
  },
  {
    id: "c3d4e5f6-7890-abcd-ef12-345678901234",
    publicId: "S-3455",
    name: "DataGuard Analytics",
    legalName: "DataGuard Analytics GmbH",
    state: "active",
    entityType: "Technology Services",
    materialityLevel: "Standard",
    materialitySubstitutability: "Easy",
    infosecCriticalityTier: "3",
    infosecSensitivityTier: "C",
    servicingEntities: ["Wise Europe SA"],
    cifsSupported: [],
    tags: [
      "Materiality Impact = High",
      "Materiality Substitutability = Easy",
      "Third Party Supplier = TRUE",
      "SUPPORTIVE = TRUE",
      "Data Processed = TRUE",
      "BSP - Market Tier 2",
      "Criticality = Tier 3",
    ],
  },
  {
    id: "d4e5f678-90ab-cdef-1234-567890123456",
    publicId: "S-2590",
    name: "SecureVault Inc",
    legalName: "SecureVault Inc.",
    state: "active",
    entityType: "Banking Services",
    // Declared as "Non material" but tags indicate "Material" → mismatch!
    materialityLevel: "Non material",
    materialitySubstitutability: "Impossible",
    infosecCriticalityTier: "1",
    infosecSensitivityTier: "A",
    servicingEntities: ["Wise US Inc", "Wise Payments Ltd"],
    cifsSupported: ["CIF-001"],
    tags: [
      "Materiality Impact = High",
      "Materiality Substitutability = Impossible",
      "Banking Supplier",
      "BSP - Market Tier 1",
      "Other types of non-public data = TRUE",
      "Data Processed = TRUE",
      "PII Processed = TRUE",
      "Criticality = Tier 1",
    ],
  },
  {
    id: "e5f67890-abcd-ef12-3456-789012345678",
    publicId: "S-4001",
    name: "RegTech Compliance",
    legalName: "RegTech Compliance Pty Ltd",
    state: "pending",
    entityType: "Compliance Services",
    materialityLevel: "Standard",
    materialitySubstitutability: "Instant Replacement",
    infosecCriticalityTier: "2",
    infosecSensitivityTier: "B",
    servicingEntities: ["Wise Australia Pty Ltd"],
    cifsSupported: [],
    tags: [
      "Materiality Impact = Low",
      "Materiality Substitutability = Instant Replacement",
      "Third Party Supplier = TRUE",
      "CIF = TRUE",
      "Data Processed = TRUE",
      "Tier B (BP)",
      "BSP - Market Tier 2",
      "Criticality = Tier 2",
    ],
  },
  {
    id: "f6789012-cdef-1234-5678-901234567890",
    publicId: "S-5010",
    name: "PayBridge Global",
    legalName: "PayBridge Global Inc",
    state: "active",
    entityType: "Payment Services",
    // Declared "Material" but tags say "Non-Material" → mismatch!
    materialityLevel: "Material",
    materialitySubstitutability: "Easy",
    infosecCriticalityTier: "2",
    infosecSensitivityTier: "B",
    servicingEntities: ["Wise Payments Ltd"],
    cifsSupported: ["CIF-002"],
    tags: [
      "Materiality Impact = Low",
      "Materiality Substitutability = Easy",
      "CIF = TRUE",
      "Third Party Supplier = TRUE",
      "Banking Supplier",
      "BSP - Market Tier 2",
      "Data Processed = TRUE",
    ],
  },
];

export const auditRequests: AuditRequest[] = [
  {
    requestUUID: "req-001-uuid",
    requestId: "REQ-5521",
    name: "Annual Security Assessment",
    supplier: "Banco BICE",
    workflow: "Baseline Assessment",
    state: "In Progress",
    stage: "Supplier Review",
    type: "Assessment",
    priority: "High",
    tags: [
      "Materiality Substitutability = Easy",
      "Materiality Impact = Low",
      "Banking Supplier",
      "Other types of non-public data = TRUE",
      "Data Processed = TRUE",
      "Tier C (BP)",
      "PII Processed = TRUE",
      "BSP - Market Tier 1",
    ],
    createdOn: "2025-11-15",
    dueDate: "2026-04-15",
    assignees: "Maria Johansson",
    materialityLevel: "Non material",
    infosecCriticality: "3",
    infosecSensitivity: "B",
    questions: {
      "baseline_main_wise_data_handling": "Yes",
      "baseline_main_wise_data_types_scope": "PII, Financial data",
      "baseline_main_encryption_data_at_rest": "Yes - AES-256",
      "baseline_main_mfa_sensitive_systems": "Yes",
      "baseline_main_penetration_tests_annual": "Yes",
      "baseline_main_incident_mgmt_policy": "Yes",
    },
  },
  {
    requestUUID: "req-002-uuid",
    requestId: "REQ-5522",
    name: "KYC Due Diligence Review",
    supplier: "Banco BICE",
    workflow: "KYC Assessment",
    state: "Pending",
    stage: "Internal Review",
    type: "Due Diligence",
    priority: "Medium",
    tags: [
      "Materiality Substitutability = Easy",
      "Materiality Impact = Low",
      "Banking Supplier",
      "PII Processed = TRUE",
      "BSP - Market Tier 1",
    ],
    createdOn: "2026-01-10",
    dueDate: "2026-05-10",
    assignees: "Erik Lindström",
    materialityLevel: "Non material",
    infosecCriticality: "3",
    infosecSensitivity: "B",
    questions: {
      "baseline_main_infosec_manager_responsible": "Yes",
      "baseline_main_background_checks_new_hires": "Yes",
      "baseline_main_access_mgmt_policy": "Yes",
    },
  },
  {
    requestUUID: "req-003-uuid",
    requestId: "REQ-5610",
    name: "Onboarding Security Review",
    supplier: "CloudPay Solutions",
    workflow: "Standard Assessment",
    state: "In Progress",
    stage: "Vendor Questionnaire",
    type: "Assessment",
    priority: "Critical",
    tags: [
      "Materiality Impact = High",
      "Materiality Substitutability = Difficult",
      "Banking Supplier",
      "BSP - Market Tier 1",
      "Other types of non-public data = TRUE",
      "Data Processed = TRUE",
      "Tier C (BP)",
    ],
    createdOn: "2026-02-01",
    dueDate: "2026-06-01",
    assignees: "Anna Virtanen",
    materialityLevel: "Material",
    infosecCriticality: "1",
    infosecSensitivity: "A",
    questions: {
      "baseline_main_wise_data_handling": "Yes",
      "baseline_main_encryption_data_at_rest": "Yes - AES-256",
      "baseline_main_encryption_data_in_transit": "TLS 1.3",
      "baseline_main_penetration_tests_annual": "Yes",
      "baseline_main_vuln_scanning_monthly": "Yes",
      "baseline_main_logging_monitoring_247": "Yes",
      "baseline_main_incident_response_team": "Yes",
      "baseline_main_third_party_risk_assessments": "No",
    },
  },
  {
    requestUUID: "req-004-uuid",
    requestId: "REQ-5611",
    name: "Identity & Access Management Survey",
    supplier: "Nordic KYC Services",
    workflow: "IAM Assessment",
    state: "Completed",
    stage: "Closed",
    type: "Survey",
    priority: "Medium",
    tags: [
      "Materiality Impact = Low",
      "Materiality Substitutability = Easy",
      "CIF = TRUE",
      "Third Party Supplier = TRUE",
      "Tier B (BP)",
      "Data Processed = TRUE",
      "PII Processed = TRUE",
      "BSP - Market Tier 1",
      "Criticality = Tier 2",
    ],
    createdOn: "2025-09-20",
    dueDate: "2026-01-20",
    assignees: "Tomislav Kovač",
    materialityLevel: "Non material",
    infosecCriticality: "2",
    infosecSensitivity: "A",
    questions: {
      "baseline_main_access_mgmt_policy": "Yes",
      "baseline_main_mfa_sensitive_systems": "Yes",
      "baseline_main_user_access_removal": "Yes",
      "baseline_main_authentication_mechanisms": "SSO + MFA",
    },
  },
  {
    requestUUID: "req-005-uuid",
    requestId: "REQ-5700",
    name: "Data Processing Impact Assessment",
    supplier: "DataGuard Analytics",
    workflow: "DPIA",
    state: "In Progress",
    stage: "Risk Analysis",
    type: "Assessment",
    priority: "Low",
    tags: [
      "Materiality Impact = High",
      "Materiality Substitutability = Easy",
      "Third Party Supplier = TRUE",
      "SUPPORTIVE = TRUE",
      "Data Processed = TRUE",
      "BSP - Market Tier 2",
      "Criticality = Tier 3",
    ],
    createdOn: "2026-01-25",
    dueDate: "2026-07-25",
    assignees: "Maria Johansson",
    materialityLevel: "Standard",
    infosecCriticality: "3",
    infosecSensitivity: "C",
    questions: {
      "baseline_main_wise_data_handling": "Yes",
      "baseline_main_data_processing_locations": "Germany, Ireland",
      "baseline_main_security_incident_last12mo": "No",
      "baseline_main_infosec_policies_defined": "Yes",
    },
  },
  {
    requestUUID: "req-006-uuid",
    requestId: "REQ-5701",
    name: "Penetration Test Review",
    supplier: "SecureVault Inc",
    workflow: "Security Assessment",
    state: "In Progress",
    stage: "Evidence Collection",
    type: "Assessment",
    priority: "Critical",
    tags: [
      "Materiality Impact = High",
      "Materiality Substitutability = Impossible",
      "Banking Supplier",
      "BSP - Market Tier 1",
      "Other types of non-public data = TRUE",
      "Data Processed = TRUE",
      "PII Processed = TRUE",
      "Criticality = Tier 1",
    ],
    createdOn: "2026-02-10",
    dueDate: "2026-05-10",
    assignees: "Erik Lindström",
    materialityLevel: "Material",
    infosecCriticality: "1",
    infosecSensitivity: "A",
    questions: {
      "baseline_main_penetration_tests_annual": "Yes",
      "baseline_main_vuln_scanning_monthly": "Yes",
      "baseline_main_vuln_remediation_cvss": "Yes",
      "baseline_main_encryption_data_at_rest": "Yes - AES-256",
      "baseline_main_encryption_data_in_transit": "TLS 1.2",
      "baseline_main_logging_monitoring_247": "Yes",
      "baseline_main_incident_response_team": "Yes",
      "baseline_main_third_party_involvement": "No",
    },
  },
  {
    requestUUID: "req-007-uuid",
    requestId: "REQ-5702",
    name: "SCA Compliance Check",
    supplier: "SecureVault Inc",
    workflow: "SCA Assessment",
    state: "Pending",
    stage: "Awaiting Supplier",
    type: "Compliance",
    priority: "High",
    tags: [
      "Materiality Impact = High",
      "Materiality Substitutability = Impossible",
      "Banking Supplier",
      "PII Processed = TRUE",
      "BSP - Market Tier 1",
      "Criticality = Tier 1",
    ],
    createdOn: "2026-03-01",
    dueDate: "2026-06-01",
    assignees: "Anna Virtanen",
    materialityLevel: "Material",
    infosecCriticality: "1",
    infosecSensitivity: "A",
    questions: {
      "baseline_main_mfa_sensitive_systems": "Yes",
      "baseline_main_authentication_mechanisms": "FIDO2 + OTP",
      "baseline_main_access_mgmt_policy": "Yes",
    },
  },
  {
    requestUUID: "req-008-uuid",
    requestId: "REQ-5800",
    name: "Vendor Risk Assessment",
    supplier: "RegTech Compliance",
    workflow: "Risk Assessment",
    state: "In Progress",
    stage: "Questionnaire Sent",
    type: "Assessment",
    priority: "Medium",
    tags: [
      "Materiality Impact = Low",
      "Materiality Substitutability = Instant Replacement",
      "Third Party Supplier = TRUE",
      "CIF = TRUE",
      "Data Processed = TRUE",
      "Tier B (BP)",
      "BSP - Market Tier 2",
      "Criticality = Tier 2",
    ],
    createdOn: "2026-02-20",
    dueDate: "2026-08-20",
    assignees: "Tomislav Kovač",
    materialityLevel: "Standard",
    infosecCriticality: "2",
    infosecSensitivity: "B",
    questions: {
      "baseline_main_wise_data_handling": "Yes",
      "baseline_main_third_party_risk_assessments": "Yes",
      "baseline_main_critical_third_party_reviews": "No",
      "baseline_main_infosec_policies_defined": "Yes",
      "baseline_main_security_awareness_training": "Yes",
    },
  },
  {
    requestUUID: "req-009-uuid",
    requestId: "REQ-5900",
    name: "Banking Integration Review",
    supplier: "PayBridge Global",
    workflow: "Baseline Assessment",
    state: "In Progress",
    stage: "Supplier Review",
    type: "Assessment",
    priority: "High",
    tags: [
      "Materiality Impact = Low",
      "Materiality Substitutability = Easy",
      "CIF = TRUE",
      "Third Party Supplier = TRUE",
      "Banking Supplier",
      "BSP - Market Tier 2",
      "Data Processed = TRUE",
    ],
    createdOn: "2026-03-05",
    dueDate: "2026-06-15",
    assignees: "Maria Johansson",
    materialityLevel: "Non material",
    infosecCriticality: "2",
    infosecSensitivity: "B",
    questions: {
      "baseline_main_wise_data_handling": "Yes",
      "baseline_main_encryption_data_at_rest": "No",
      "baseline_main_penetration_tests_annual": "No",
      "baseline_main_incident_mgmt_policy": "Yes",
      "baseline_main_infosec_manager_responsible": "Yes",
    },
  },
];

// Human-readable question labels for display
export const questionLabels: Record<string, string> = {
  "baseline_main_wise_data_handling": "Wise data handling",
  "baseline_main_wise_data_types_scope": "Wise data types in scope",
  "baseline_main_encryption_data_at_rest": "Encryption at rest",
  "baseline_main_encryption_data_in_transit": "Encryption in transit",
  "baseline_main_mfa_sensitive_systems": "MFA for sensitive systems",
  "baseline_main_penetration_tests_annual": "Annual penetration tests",
  "baseline_main_vuln_scanning_monthly": "Monthly vulnerability scans",
  "baseline_main_vuln_remediation_cvss": "CVSS-based remediation",
  "baseline_main_logging_monitoring_247": "24/7 logging & monitoring",
  "baseline_main_incident_mgmt_policy": "Incident management policy",
  "baseline_main_incident_response_team": "Incident response team",
  "baseline_main_incident_response_plan": "Incident response plan",
  "baseline_main_infosec_manager_responsible": "InfoSec manager designated",
  "baseline_main_infosec_policies_defined": "InfoSec policies documented",
  "baseline_main_background_checks_new_hires": "Background checks",
  "baseline_main_access_mgmt_policy": "Access management policy",
  "baseline_main_user_access_removal": "User access removal",
  "baseline_main_authentication_mechanisms": "Authentication mechanisms",
  "baseline_main_security_awareness_training": "Security awareness training",
  "baseline_main_third_party_risk_assessments": "Third-party risk assessments",
  "baseline_main_critical_third_party_reviews": "Critical third-party reviews",
  "baseline_main_third_party_involvement": "Third-party involvement",
  "baseline_main_data_processing_locations": "Data processing locations",
  "baseline_main_security_incident_last12mo": "Security incident (12mo)",
};
